services:
  api:
    build:
      context: ./../../
      dockerfile: ./containers/api/Dockerfile
    restart: always
    environment:
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 8000:8000
    networks:
      - internal-network
    volumes:
      - type: bind
        source: ./../../src
        target: /src