services:
  dev:
    build:
      context: ./../../
      dockerfile: ./containers/dev/Dockerfile
    restart: always
    ports:
      - 8000:8000
    networks:
      - internal-network
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./../../src
        target: /src